name: Run Tests
on:
  push

jobs:
  build-and-upload-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the typescript code
        run: yarn build
      - uses: actions/upload-artifact@main
        with:
          name: build artifacts
          path: build/

  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, and test
        run: yarn test

  build-to-npm:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - run-tests
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Configure NPM authentication
      run: |
        yarn config set npmAlwaysAuth true
        yarn config set npmAuthToken ${{ secrets.NPM_TOKEN }}
    - name: Publish to yarn/npm
      run: yarn npm publish

  build-to-github-packages:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - run-tests
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Configure Github Packages authentication
      run: |
        yarn config set npmAlwaysAuth true
        yarn config set npmRegistryServer https://npm.pkg.github.com
        yarn config set npmPublishRegistry https://npm.pkg.github.com
        yarn config set npmAuthToken ${{ secrets.GITHUB_TOKEN }}
    - name: Publish to Github packages
      run: yarn npm publish
